/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#ff6b6d',
        'inverse-on-surface': '#edf1f5',
        'tertiary-container': '#6d0012',
        'primary-fixed-dim': '#a9c7ff',
        'primary': '#001e42',
        'outline-variant': '#c3c6d1',
        'on-primary-container': '#729ce2',
        'error-container': '#ffdad6',
        'secondary': '#515f74',
        'on-error-container': '#93000a',
        'surface-variant': '#dfe3e7',
        'on-secondary-fixed-variant': '#3a485b',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface': '#f6fafe',
        'secondary-fixed': '#d5e3fc',
        'background': '#f6fafe',
        'primary-container': '#003368',
        'on-tertiary-fixed-variant': '#92001c',
        'on-primary-fixed-variant': '#0e4686',
        'on-background': '#171c1f',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#305ea0',
        'primary-fixed': '#d6e3ff',
        'surface-container-low': '#f0f4f8',
        'surface-bright': '#f6fafe',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001b3d',
        'surface-container-high': '#e4e9ed',
        'outline': '#737780',
        'on-error': '#ffffff',
        'inverse-surface': '#2c3134',
        'tertiary': '#450008',
        'on-tertiary-fixed': '#410007',
        'on-surface': '#171c1f',
        'secondary-container': '#d5e3fc',
        'on-secondary-fixed': '#0d1c2e',
        'surface-container-highest': '#dfe3e7',
        'surface-container': '#eaeef2',
        'secondary-fixed-dim': '#b9c7df',
        'on-primary': '#ffffff',
        'on-secondary-container': '#57657a',
        'tertiary-fixed-dim': '#ffb3b1',
        'tertiary-fixed': '#ffdad8',
        'on-surface-variant': '#43474f',
        'surface-dim': '#d6dade',
        'inverse-primary': '#a9c7ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Work Sans'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
}
